spring:
  data:
    cassandra:
      contact-points:
        - cassandra
      keyspace-name: discord
      local-datacenter: datacenter1
      connection:
        connect-timeout: 30s
        init-query-timeout: 30s
      request:
        timeout: 20s
        consistency: local_one
      pool:
        idle-timeout: 10s
        heartbeat-interval: 30s
  cassandra:
    keyspace-name: discord
    schema-action: CREATE_IF_NOT_EXISTS

discord:
  token: "Your-Token"
  reply-for-me: false
  token-username: optimusmac_
  auto-runner: true
  streams:
    - guildId: "411933527282810903"
      channelId: "1361039180142084226"
      type: word #word/numeric
    - guildId: "411933527282810903"
      channelId: "1361038778436681782"
      type: numeric #word/numeric